# Generated by Django 3.0 on 2019-12-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=32)),
                ('operation_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_from', to='cashes.Cash')),
                ('operation_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_to', to='cashes.Cash')),
            ],
        ),
    ]
