# Generated by Django 3.0 on 2019-12-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='same_owner',
            field=models.BooleanField(default=False, verbose_name='Transaction is between one profile cashes'),
        ),
    ]
